// Generated by CoffeeScript 1.3.3
/*
to COMPILE
"coffee --watch --bare --compile --output js/ js/coffee/*.coffee"
at HanselMock/
*/

/* ---------チュートリアル---------
*/

var dispTutArrowImg, dispTutInfoP, disp_WelcomeToHanselImg, disp_explain_UI, disp_final_logo, disp_final_subtitle, disp_massage_2, hideArrowImg, hide_explain_UI, hide_final_logo, hide_final_subtitle, hide_massage_2, tutrialInit;

tutrialInit = function() {
  var arrowTimer;
  setTimeout(disp_WelcomeToHanselImg, 1500);
  setTimeout(dispTutInfoP, 3000);
  arrowTimer = setTimeout(dispTutArrowImg, 4500);
  $("#pagesBox").bind("turning", function(event, page, view) {
    console.log(" - - - - turning event fire! - - - - ");
    console.log("page:" + page);
    console.log("view:" + view);
    hide_final_logo();
    hide_final_subtitle();
    hide_explain_UI();
    return hide_massage_2();
  });
  return $("#pagesBox").bind("turned", function(event, page, view) {
    console.log("-------- turned event fire! --------");
    console.log("page:" + page);
    console.log("view:" + view);
    clearTimeout(arrowTimer);
    hideArrowImg();
    if (page === 6 || page === 7) {
      setTimeout(disp_explain_UI, 500);
      arrowTimer = setTimeout(dispTutArrowImg, 4300);
    }
    if (page === 8 || page === 9) {
      setTimeout(disp_massage_2, 500);
      arrowTimer = setTimeout(dispTutArrowImg, 5000);
    }
    if (page === 10) {
      setTimeout(disp_final_logo, 1500);
      return setTimeout(disp_final_subtitle, 4000);
    }
  });
};

disp_WelcomeToHanselImg = function() {
  return $("#welcomeToHanselImg").css({
    opacity: 1
  });
};

dispTutInfoP = function() {
  return $("#hanselMockTutrialInfo").css({
    opacity: 1
  });
};

dispTutArrowImg = function() {
  return $("#tutrialArrow").css({
    opacity: 0.8,
    top: "303px",
    left: "73%"
  });
};

hideArrowImg = function() {
  var $arrow;
  $arrow = $("#tutrialArrow");
  $arrow.css({
    opacity: 0
  });
  return setTimeout((function() {
    return $arrow.css({
      left: 0,
      top: "100%"
    });
  }), 1000);
};

disp_explain_UI = function() {
  return $("#tutrial_explainUI").css({
    opacity: 0.8,
    top: "528px",
    left: "7%"
  });
};

hide_explain_UI = function() {
  return $("#tutrial_explainUI").css({
    opacity: 0,
    top: "-100px"
  });
};

disp_massage_2 = function() {
  return $("#tutrial_message2").css({
    opacity: 0.8,
    top: "468px",
    left: "20%"
  });
};

hide_massage_2 = function() {
  return $("#tutrial_message2").css({
    opacity: 0,
    top: "-100px"
  });
};

disp_final_logo = function() {
  return $("#finalHanselLogo").css({
    opacity: 1
  });
};

hide_final_logo = function() {
  return $("#finalHanselLogo").css({
    opacity: 0
  });
};

disp_final_subtitle = function() {
  return $("#finalSubTitle").css({
    opacity: 1
  });
};

hide_final_subtitle = function() {
  return $("#finalSubTitle").css({
    opacity: 0
  });
};

/* ---------ここまでチュートリアル---------
*/

